### ISSUE TITLE
Implement commands for service booking

### ISSUE THREAD

**Issue by sreycodes** [cs2103-ay1819s2-t12-1/main#10]
Implement AddBookingCommand, EditBookingCommand, DeleteBookingCommand, ListBookingCommand

**Comment by nerrons** [comment]
Perhaps AddServiceCommand, ... etc? Cuz booking is reserved for booking rooms

**Comment by sreycodes** [comment]
The thing is there is a difference between service and booking service. I propose "reservation" for rooms and "booking" for services @nerrons

**Comment by sreycodes** [comment]
Implemented by #79
